### ISSUE TITLE
Documents & script fix

### ISSUE THREAD

**Issue by ami-GS** [microsoft/netperf#182]
Because the script doesn't work by default based on document, I checked the content and found the issues. This is not reliable to run.

-u and -p are also required parameter
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/docs/machines.md?plain=1#L103

Why ssh-copy-id is needed after doing in the script
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/docs/machines.md?plain=1#L105

Too open. 400
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/setup-runner-linux.sh#L80

I forget, but maybe this script need to be executed in the directory. or showing error.
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/setup-runner-linux.sh#L124

Sleep is not needed
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/setup-runner-linux.sh#L91
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/setup-runner-linux.sh#L133

`~` is home directory. try `echo ~`
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/setup-runner-linux.sh#L54

if you want to split role for server/client (as doing by github token), openssh-server and its config is not needed on client. but this is recommendation.
https://github.com/microsoft/netperf/blob/9c70821f997d938e64d0ab147dce6fa632525982/setup-runner-linux.sh#L64

**Comment by ProjectsByJackHe** [comment]
Thanks @ami-GS for the suggestions! I am looking to improve the documentation for lab Linux install / configuration, and I realize that part of the problem with Linux is the step where we need to ssh-copy the public keys. The problem is, our lab machine VMs haven't been assigned an IP yet, so there is no way to copy the public keys over... No matter how we spin it, we first need to setup `ping` to get everything to work. The plan going forward is to reconcile the docs to reflect our learnings, I will remove ssh-copy and the chmod 777 bits as per your suggestions.
